# Common costmap parameters
robot_radius: 0.15
inflation_radius: 0.30
obstacle_range: 2.5
raytrace_range: 3.0

# Robot footprint (rectangle)
footprint: [[-0.15, -0.10], [-0.15, 0.10], [0.15, 0.10], [0.15, -0.10]]

