# move_base general parameters
base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

planner_frequency: 1.0
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# goal tolerances
xy_goal_tolerance: 0.15
yaw_goal_tolerance: 0.25

